// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVipZ9MBUKz-8phgOFDvf_ZKV7pxom1DY',
    appId: '1:761178190932:web:0794876b7264d65a9d69c1',
    messagingSenderId: '761178190932',
    projectId: 'inturn-8ec4a',
    authDomain: 'inturn-8ec4a.firebaseapp.com',
    storageBucket: 'inturn-8ec4a.appspot.com',
    measurementId: 'G-KC7ZDG7CGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3j7l29qm9ecWnnLGjiMSxhx5PkCnv8s',
    appId: '1:761178190932:android:dc9fa194780844c79d69c1',
    messagingSenderId: '761178190932',
    projectId: 'inturn-8ec4a',
    storageBucket: 'inturn-8ec4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPaUjk-GQx-3vW2XMbN2np8dCfS2eIAE',
    appId: '1:761178190932:ios:1692a70eb48159f39d69c1',
    messagingSenderId: '761178190932',
    projectId: 'inturn-8ec4a',
    storageBucket: 'inturn-8ec4a.appspot.com',
    iosClientId: '761178190932-220ni1tcajmdkvjk2ssceu05c17hgh4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.inturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPaUjk-GQx-3vW2XMbN2np8dCfS2eIAE',
    appId: '1:761178190932:ios:1692a70eb48159f39d69c1',
    messagingSenderId: '761178190932',
    projectId: 'inturn-8ec4a',
    storageBucket: 'inturn-8ec4a.appspot.com',
    iosClientId: '761178190932-220ni1tcajmdkvjk2ssceu05c17hgh4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.inturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVipZ9MBUKz-8phgOFDvf_ZKV7pxom1DY',
    appId: '1:761178190932:web:654a48b2bb382f909d69c1',
    messagingSenderId: '761178190932',
    projectId: 'inturn-8ec4a',
    authDomain: 'inturn-8ec4a.firebaseapp.com',
    storageBucket: 'inturn-8ec4a.appspot.com',
    measurementId: 'G-G3T9QKYWGX',
  );
}
